-- Populates Spanish labels for seeded service types after ADD COLUMN name_es (upgrade path).
UPDATE service_type SET name_es = 'Cambio de aceite del motor' WHERE id = 1;
UPDATE service_type SET name_es = 'Cambio de filtro de aceite del motor' WHERE id = 2;
UPDATE service_type SET name_es = 'Cambio de filtro de aire del motor' WHERE id = 3;
UPDATE service_type SET name_es = 'Cambio de filtro de habitáculo / climatización' WHERE id = 4;
UPDATE service_type SET name_es = 'Cambio de filtro de combustible' WHERE id = 5;
UPDATE service_type SET name_es = 'Cambio de bujías' WHERE id = 6;
UPDATE service_type SET name_es = 'Limpieza / sustitución del refrigerante' WHERE id = 7;
UPDATE service_type SET name_es = 'Purga / sustitución del líquido de frenos' WHERE id = 8;
UPDATE service_type SET name_es = 'Cambio de pastillas de freno' WHERE id = 9;
UPDATE service_type SET name_es = 'Rectificado / cambio de discos de freno' WHERE id = 10;
UPDATE service_type SET name_es = 'Servicio de aceite de transmisión' WHERE id = 11;
UPDATE service_type SET name_es = 'Servicio de aceite de diferencial / transmisión final' WHERE id = 12;
UPDATE service_type SET name_es = 'Servicio de líquido de dirección asistida' WHERE id = 13;
UPDATE service_type SET name_es = 'Rotación de neumáticos' WHERE id = 14;
UPDATE service_type SET name_es = 'Alineación de dirección' WHERE id = 15;
UPDATE service_type SET name_es = 'Sustitución de neumáticos / montaje y balanceo' WHERE id = 16;
UPDATE service_type SET name_es = 'Prueba / sustitución de batería' WHERE id = 17;
UPDATE service_type SET name_es = 'Cambio de correa de accesorios / poli-V' WHERE id = 18;
UPDATE service_type SET name_es = 'Servicio de correa de distribución / cadena' WHERE id = 19;
UPDATE service_type SET name_es = 'Inspección de suspensión / amortiguadores' WHERE id = 20;
UPDATE service_type SET name_es = 'Cambio de escobillas del limpiaparabrisas' WHERE id = 21;
UPDATE service_type SET name_es = 'Inspección multipunto general' WHERE id = 22;
UPDATE service_type SET name_es = 'Limpieza y lubricación de cadena (motocicleta)' WHERE id = 23;
UPDATE service_type SET name_es = 'Cambio de cadena / piñones (motocicleta)' WHERE id = 24;
UPDATE service_type SET name_es = 'Revisión de holguras de válvulas (motocicleta)' WHERE id = 25;
UPDATE service_type SET name_es = 'Inspección de presión y dibujo de neumáticos' WHERE id = 26;
UPDATE service_type SET name_es = 'Servicio de líquido limpiaparabrisas' WHERE id = 27;
UPDATE service_type SET name_es = 'Inspección de mangueras y correa de accesorios' WHERE id = 28;
UPDATE service_type SET name_es = 'Cambio de aceite de caja manual' WHERE id = 29;
UPDATE service_type SET name_es = 'Servicio de líquido hidráulico del embrague' WHERE id = 30;
UPDATE service_type SET name_es = 'Servicio del conjunto de embrague' WHERE id = 31;
UPDATE service_type SET name_es = 'Servicio de aceite de la caja de transferencia (4x4/AWD)' WHERE id = 32;
UPDATE service_type SET name_es = 'Servicio de rodamientos de rueda' WHERE id = 33;
UPDATE service_type SET name_es = 'Servicio de rótulas y terminales de dirección' WHERE id = 34;
UPDATE service_type SET name_es = 'Servicio de cremallera / bomba de dirección' WHERE id = 35;
UPDATE service_type SET name_es = 'Inspección del radiador y sistema de refrigeración' WHERE id = 36;
UPDATE service_type SET name_es = 'Cambio de bomba de agua' WHERE id = 37;
UPDATE service_type SET name_es = 'Cambio de termostato' WHERE id = 38;
UPDATE service_type SET name_es = 'Servicio de bobinas / cables de encendido' WHERE id = 39;
UPDATE service_type SET name_es = 'Servicio de inyectores / admisión' WHERE id = 40;
UPDATE service_type SET name_es = 'Cambio de sonda lambda' WHERE id = 41;
UPDATE service_type SET name_es = 'Servicio de refrigerante A/C y detección de fugas' WHERE id = 42;
UPDATE service_type SET name_es = 'Inspección de iluminación exterior / bombillas' WHERE id = 43;
UPDATE service_type SET name_es = 'Inspección de seguridad vehicular (estatal)' WHERE id = 44;
UPDATE service_type SET name_es = 'Prueba / inspección de emisiones' WHERE id = 45;
UPDATE service_type SET name_es = 'Servicio de filtro de combustible diésel' WHERE id = 46;
UPDATE service_type SET name_es = 'Relleno de AdBlue (DEF)' WHERE id = 47;
UPDATE service_type SET name_es = 'Servicio de filtro de partículas diésel (DPF)' WHERE id = 48;
UPDATE service_type SET name_es = 'Servicio de turbocompresor / intercooler' WHERE id = 49;
UPDATE service_type SET name_es = 'Servicio del sistema PCV' WHERE id = 50;
UPDATE service_type SET name_es = 'Servicio del sistema EGR' WHERE id = 51;
UPDATE service_type SET name_es = 'Inspección de batería de alta tensión (híbrido/EV)' WHERE id = 52;
UPDATE service_type SET name_es = 'Servicio de batería auxiliar 12 V (híbrido/EV)' WHERE id = 53;
UPDATE service_type SET name_es = 'Cambio de aceite de horquillas (motocicleta)' WHERE id = 54;
UPDATE service_type SET name_es = 'Purga del sistema de frenos (motocicleta)' WHERE id = 55;
UPDATE service_type SET name_es = 'Diagnóstico ABS / control de tracción' WHERE id = 56;
UPDATE service_type SET name_es = 'Sustitución del alternador' WHERE id = 57;
UPDATE service_type SET name_es = 'Sustitución del motor de arranque' WHERE id = 58;
UPDATE service_type SET name_es = 'Desinfección de habitáculo / tratamiento de olores HVAC (opcional)' WHERE id = 59;
UPDATE service_type SET name_es = 'Reparación de impactos en parabrisas' WHERE id = 60;
